-- 2026-03-04 : Reinitialisation des donnees pour les schemas dev et staging

TRUNCATE TABLE IF EXISTS dev.Assignation RESTART IDENTITY CASCADE;
TRUNCATE TABLE IF EXISTS dev.Distance RESTART IDENTITY CASCADE;
TRUNCATE TABLE IF EXISTS dev.token_expiration RESTART IDENTITY CASCADE;
TRUNCATE TABLE IF EXISTS dev.reservation RESTART IDENTITY CASCADE;
TRUNCATE TABLE IF EXISTS dev.Vehicule RESTART IDENTITY CASCADE;
TRUNCATE TABLE IF EXISTS dev.Parametre RESTART IDENTITY CASCADE;
TRUNCATE TABLE IF EXISTS dev.Hotel RESTART IDENTITY CASCADE;

TRUNCATE TABLE IF EXISTS staging.reservation RESTART IDENTITY CASCADE;
TRUNCATE TABLE IF EXISTS staging.Hotel RESTART IDENTITY CASCADE;
