TRUNCATE TABLE staging.Assignation RESTART IDENTITY CASCADE;
TRUNCATE TABLE staging.Distance RESTART IDENTITY CASCADE;
TRUNCATE TABLE staging.token_expiration RESTART IDENTITY CASCADE;
TRUNCATE TABLE staging.reservation RESTART IDENTITY CASCADE;
TRUNCATE TABLE staging.Vehicule RESTART IDENTITY CASCADE;
TRUNCATE TABLE staging.Parametre RESTART IDENTITY CASCADE;
TRUNCATE TABLE staging.Hotel RESTART IDENTITY CASCADE;


