-- 2026-03-04 : Reinitialisation des donnees pour les schemas dev 

TRUNCATE TABLE dev.Assignation RESTART IDENTITY CASCADE;
TRUNCATE TABLE dev.Distance RESTART IDENTITY CASCADE;
TRUNCATE TABLE dev.token_expiration RESTART IDENTITY CASCADE;
TRUNCATE TABLE dev.reservation RESTART IDENTITY CASCADE;
TRUNCATE TABLE dev.Vehicule RESTART IDENTITY CASCADE;
TRUNCATE TABLE dev.Parametre RESTART IDENTITY CASCADE;
TRUNCATE TABLE dev.Hotel RESTART IDENTITY CASCADE;
