-- 2026-03-10 : Reinitialisation des donnees pour les schemas staging (ajout Trajet/TrajetEtape)
TRUNCATE TABLE staging.Assignation RESTART IDENTITY CASCADE;
TRUNCATE TABLE staging.Distance RESTART IDENTITY CASCADE;
TRUNCATE TABLE staging.token_expiration RESTART IDENTITY CASCADE;
TRUNCATE TABLE staging.reservation RESTART IDENTITY CASCADE;
TRUNCATE TABLE staging.Vehicule RESTART IDENTITY CASCADE;
TRUNCATE TABLE staging.Parametre RESTART IDENTITY CASCADE;
TRUNCATE TABLE staging.Hotel RESTART IDENTITY CASCADE;E
TRUNCATE TABLE staging.Trajet RESTART IDENTITY CASCADE;
TRUNCATE TABLE staging.TrajetEtape RESTART IDENTITY CASCADE;


